---
title: "PCA(new)"
author: "Priyanka"
date: "22/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}


pc <- prcomp(df_noCorr_scaled)
plot(pc)

plot(pc,type = "l")

```


```{r}

summary(pc)

```




```{r}

library(scatterplot3d)

scatterplot3d(pc$x[,1:3],pch = 16, color = "blue")


library(rgl)
# Multi 3D plot
plot3d(pc$x[,1], pc$x[,2], pc$x[,3],col = "blue")
#plot3d(pc$x[,2], pc$x[,3], pc$x[,4],col = "blue")

```
Kmeans

```{r}

comp <- data.frame(pc$x[,1:4])

kcenters <- c(2,4)
kcenters

set.seed(123)

pckmclust2 <- kmeans(comp,2, nstart=50,iter.max = 15)
pckmclust4 <- kmeans(comp,4, nstart=50,iter.max = 15)

pckm2_labels <- pckmclust2$cluster # klabels for getting labelled data
head(pckm2_labels, n = 50)
pckm4_labels <- pckmclust4$cluster # klabels for getting labelled data
head(pckm4_labels, n = 50)

```


```{r}
library(tidyverse)

df_allF_pckm2_labeled<-df_allF%>%
  mutate(label = pckm2_labels)
df_allF_scaled_pckm2_labeled<-df_allF_scaled%>%
  mutate(label = pckm2_labels)
df_allF_pckm4_labeled<-df_allF%>%
  mutate(label = pckm4_labels)
df_allF_scaled_pckm4_labeled<-df_allF_scaled%>%
  mutate(label = pckm4_labels)

df_grouped_pckm<-df_allF_pckm2_labeled%>%
  group_by(label)
df_split<-group_split(df_grouped_pckm)
```


```{r}

cluster_features_scaled<-data.frame(df_allF_scaled_pckm2_labeled%>%
                               group_by(label)%>%
                               summarise_each(mean))
cluster_features<-data.frame(df_allF_pckm2_labeled%>%
                               group_by(label)%>%
                               summarise_each(mean))
feature_summary_scaled<-data.frame(df_allF_scaled%>%
                               summarise_each(mean))
feature_summary<-data.frame(df_allF%>%
                               summarise_each(mean))

```


```{r}

library(r2d3)

options(scipen = 999)
f<-function(cluster_scaled,cluster)
 { cluster_plot_data<-rbind(colnames(cluster[-1]),cluster_scaled[-1],feature_summary,cluster[-1])
  rownames(cluster_plot_data)<-c("feature","scaled_cluster_feature_value","population_mean","cluster_feature_value")
  cluster_plot_data<-t(cluster_plot_data)%>%data.frame()
  print(r2d3(data = cluster_plot_data, script = "cluster_chart.js",viewer ="internal"))
  return(cluster_plot_data)
}
for (i in seq(1:2))
{
  plot_data<-f(cluster_features_scaled[i,],cluster_features[i,])
}


```

## Decision Tree

```{r}

library(caret)
library(rpart.plot)
library(e1071)

set.seed(123)
df_string_pckm2_labeled <- df_allF_pckm2_labeled
df_string_pckm2_labeled$label <- sub("^","Type ",df_string_pckm2_labeled$label) #Adding "Type" to each cluster number to make it                                                             #non numeric
trctrl <- trainControl(method = "boot", number = 10)
dtree_fit <- train(label ~., data = df_string_pckm2_labeled, method = "rpart",
                   parms = list(split = "information"),
                   trControl=trctrl,
                   tuneLength = 10)

prp(dtree_fit$finalModel, box.palette = "Reds", tweak = 1.2)

```


## Evaluation

```{r}

library(diceR)
library("clValid")



evaluate<-function(data){
  result_set<-vector("list", 3)
  result_set[1]<-dunn(clusters = data$label, Data=df_allF_scaled)
  result_set[2]<-connectivity(distance = NULL, data$label, Data = df_allF_scaled, neighbSize = 10, method = "euclidean")
  result_set[3]<-compactness(df_allF_scaled, data$label)
  print(result_set)
  return(result_set)
}

res.pca_kmeans<-evaluate(df_allF_scaled_pckm2_labeled)

```


